apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings-Boilerplate-api
  namespace: as-solv
data:
  app-settings: |
    {
      "AllowedHosts": "*" ,
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Async", "Serilog.Exceptions" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft.AspNetCore": "Warning",
            "Microsoft.EntityFrameworkCore.Database.Command": "Warning",
            "Microsoft.EntityFrameworkCore.Infrastructure": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Async",
            "Args": {
              "configure": [
                {
                  "Name": "Console",
                  "Args": {
                    "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
                    "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
                  }
                }
              ]
            }
          }
        ],
        "Enrich": [ "FromLogContext", "WithThreadId", "WithMachineName", "WithExceptionDetails" ]
      },
      "ConnectionStrings": {
        "DefaultConnection": "$(connection-string)"
      },
      "MongoDB": {
        "ConnectionString": "$(mongodb-connection)",
        "DatabaseName": "$(mongodb-name)"
      },
      "RabbitMQ": {
        "HostName": "$(queue-host)",
        "UserName": "$(queue-username)",
        "Password": "$(queue-password)",
        "Port": $(queue-port)
      }
    }
